

```{r}
require(spatstat)
require(rgdal) # change to sf/stars/terra after 2023
require(maptools)
require(doParallel)
require(foreach)
require(tidyverse)
library(gridExtra)
library(scales)
library(ggspatial)
library(ggridges)
library(shiny)
source("R/utils_Rdata.R")
```

```{r}
file_shp <- readOGR("data/monti_cristo/mc-db-95-clean.shp")

file_poly <- readOGR("data/monti_cristo/nmcpoly1.shp")

quantiles <- c(0.95)
```



```{r}

data_output <- load_data(file_shp = file_shp, file_poly = file_poly)
```

```{r}
temp <- original_pcf_function(data_output[["sp_unmark"]], 25)
```
```{r}
temp
```



```{r}
p1 <- plot(temp, ylim=c(0,4), legend=FALSE, main="Monte Carlo Envelope of the PCF - 100% of sites")
```

```{r}
# ggplot() +
#         layer_spatial(data = data_output[["sp_unmark"]], col = "black", fill="antiquewhite") +
#         theme_void()

p0 = ggplot() + 
      geom_blank() + theme_light()

thisAdd = tibble(x = temp$r, ymin = temp$lo,
                 ymax = temp$hi)
p0 = p0 + geom_ribbon(aes(x = x, ymin = ymin, ymax = ymax), data = thisAdd, 
                      fill = heat.colors(1), alpha = 0.5, lty =  "dotted", 
                      col=alpha("black", 0.2))

p3 = p0 + geom_line(aes(x=r, y=obs), data = temp, linewidth = 0.75) + 
        scale_y_continuous(limits = c(0,4.5)) + 
        xlab("r") + ylab("PCF value")

p3
```


```{r}
simulations_list <- generate_mc_envelopes(data_output[["sp_unmark"]], clusters=5, nsim = 5, portions=seq(0.5,1.0,0.1))

```

```{r}
output <- compute_mc_quantiles(simulations_list, clusters=5, nsim = 5, quantiles = quantiles, quantile_50 = TRUE)
allQuantiles_list <- output[["allQuantiles_list"]]
allQuantilesT_list <- output[["allQuantilesT_list"]]
plot_list <- output[["plot_list"]]
```

```{r}
output <- generate_robustness_scenarios_a(data_output[["sp_unmark"]], 10)
pctShockedData_list <- output[["pctShockedData_list"]]
shockedSp_list <- output[["shockedSp_list"]]
```


```{r}
source("R/utils_Rdata.R")
output_plots <- assess_robustness_scenarios_a(data_output[["sp_unmark"]], 10, pctShockedData_list, allQuantilesT_list, quantiles = quantiles)
plot_compare_exp_a <- output_plots[["plot_compare_exp_a"]]
```


```{r}
source("R/utils_Rdata.R")
output <- comparison_tool_a(data_output[["sp_unmark"]], 10, pctShockedData_list, shockedSp_list, allQuantilesT_list, quantiles, quantile_50 = TRUE)
example_plots_a <- output[["example_plots_a"]]
```


```{r}
example_plots_a
```



